language: node_js
node_js: node
cache:
  directories:
    - node_modules
before_install: npm i -g yarn
install: npm install
addons:
  firefox: "latest"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
- yarn run build
- yarn run karma.test
